### ISSUE TITLE
Notebook with code to make detector summed responses 

### ISSUE THREAD

**Issue by jjd330** [Swift-BAT/UnmaskedResponder#2]
Here's the most recent notebook I have to make detector summed responses that I used for the upper limits. Zipped because github doesn't allow .ipynb files 
[MakingDRMsFromNITRATESresps-Copy2.zip](https://github.com/Swift-BAT/UnmaskedResponder/files/11872386/MakingDRMsFromNITRATESresps-Copy2.zip)

**Comment by Tohuvavohu** [comment]
@metalphase take a look at how Jimmy constructs responses in this notebook.

Implement this simpler method (before the summation) instead of the one you currently have in the test script.

**Comment by Tohuvavohu** [comment]
And then make your own example notebook that constructs a response for a given position and add to repo as usage example.

**Comment by metalphase** [comment]
@Tohuvavohu If I'm parsing that notebook correctly, you're referring to this section where it looks like we calculate the total response dpi?

![Screenshot 2023-06-30 at 12 13 50 AM](https://github.com/Swift-BAT/UnmaskedResponder/assets/34755935/81cd3a77-ab9e-48f6-89ea-32880e3faf3d)

**Comment by Tohuvavohu** [comment]
yes that is the object of interest!
